### ISSUE TITLE
部署问题 rocketmq:v4.8.0 未找到

### ISSUE THREAD

**Issue by Miazzy** [Anthony-Dong/docker-rocketmq-cluster#1]
## 部署问题 rocketmq:v4.8.0 未找到

请问源主是否将镜像提交至公共仓库了，能否修改一下docker-compose.yml里面的具体镜像名称(rocketmq:v4.8.0)不?

**Comment by Miazzy** [comment]
非常感谢

**Comment by Anthony-Dong** [comment]
> 非常感谢

由于rocket-mq官方镜像提供的并不好用，因此采用本地构建的方式，你可以看一下 docker/image下的dockerfile文件，进行构建！

**Comment by Miazzy** [comment]
收到，非常感谢
